apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-attach-config
  {{- template "common.metadata" . }}
data:
  ikey: {{ .Values.app.iKey }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otlp
  namespace: default
data:
  otlpMetricsEndpoint: {{ .Values.app.otlpMetricsEndpoint }}
  otlpTracesEndpoint: {{ .Values.app.otlpTracesEndpoint }}