FROM alpine:3.10

ADD ./agents/current/java/applicationinsights-agent-codeless*.jar /agents/java/applicationinsights-agent-codeless.jar
ADD ./agents/current/java/appsvc.codeless /agents/java/appsvc.codeless
ADD ./zips/ApplicationInsights.json /agents/java/ApplicationInsights.json
ADD ./agents/current/nodejs /agents/node
ADD ./agents/current/core /agents/core