FROM alpine:3.10

ADD ./java/applicationinsights-agent-codeless-2.5.1-BETA.2-SNAPSHOT.jar /agents/java/applicationinsights-agent-codeless.jar
ADD ./java/ApplicationInsights.json /agents/java/ApplicationInsights.json
ADD ./java/appsvc.codeless /agents/java/appsvc.codeless
ADD ./node /agents/node
ADD ./core /agents/core