FROM alpine:3.10
#ARG AGENT_VERSION

ADD ./agents/2.8.33/java/applicationinsights-agent-codeless*.jar /agents/java/applicationinsights-agent-codeless.jar
ADD ./agents/2.8.33/java/appsvc.codeless /agents/java/appsvc.codeless
ADD ./agents/2.8.33/nodejs /agents/node
ADD ./agents/2.8.33/core /agents/core